const email='tfly58526@gmail.com';
const github='https://github.com/titfly77-cyber';
const arrow='<span class="arrow" aria-hidden="true">↗</span>';
const icons={
field:'<svg width="32" height="32" viewBox="0 0 32 32" fill="none"><path d="M7 24V14m9 10V8m9 16V12M4 26h24M7 14c-4-1-5-4-4-7 4 0 6 3 4 7Zm9-6c-2-3-1-6 2-7 3 3 2 6-2 7Zm9 4c-3-1-4-4-2-7 4 1 5 4 2 7Z" stroke="#86868b" stroke-width="1.25" stroke-linecap="round"/></svg>',
define:'<svg width="32" height="32" viewBox="0 0 32 32" fill="none"><rect x="7" y="4" width="19" height="24" rx="3" stroke="#86868b" stroke-width="1.25"/><path d="m10 11 2 2 3-4m3 3h4m-12 7 2 2 3-4m3 3h4" stroke="#86868b" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/></svg>',
build:'<svg width="32" height="32" viewBox="0 0 32 32" fill="none"><rect x="8" y="8" width="16" height="16" rx="3" stroke="#86868b" stroke-width="1.25"/><rect x="12" y="12" width="8" height="8" rx="1" stroke="#86868b" stroke-width="1.25"/><path d="M12 3v5m8-5v5M12 24v5m8-5v5M3 12h5m-5 8h5m16-8h5m-5 8h5" stroke="#86868b" stroke-width="1.25" stroke-linecap="round"/></svg>',
menu:'<svg width="24" height="24" viewBox="0 0 24 24" fill="none"><path d="M4 8h16M4 16h16" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>',
play:'<svg width="16" height="16" viewBox="0 0 16 16"><path d="m5 3 8 5-8 5Z" fill="currentColor"/></svg>',
pause:'<svg width="16" height="16" viewBox="0 0 16 16"><path d="M4 3h3v10H4zm5 0h3v10H9z" fill="currentColor"/></svg>'};
const projects=[
{slug:'tobacco',category:'INDUSTRIAL AUTOMATION',title:'Tobacco Automation Product',zh:'烟草秸秆智能清理机',desc:'Turning real agricultural workflows into automation requirements and engineering decisions.',role:'需求场景拆解 · 机械与电控',date:'2024.11 — 2025.07',owner:'机械与电控技术负责人',status:'研发项目 · 获金种子计划支持',tag:'Prototype & engineering',tags:['Embedded','Robotics','B2B','OpenCV / YOLO'],lead:'从收割后的秸秆处理需求出发，把清理任务落实为结构、视觉定位与电控协作。',coverLabel:'Workflow study',coverCaption:'清理任务的流程示意；非整机外观图。',phase:'Developed project'},
{slug:'ai-agent',category:'AI PRODUCT',title:'Project AI Agent',zh:'项目知识问答 Agent',desc:'An AI assistant concept for project context, status queries and test-case generation.',role:'知识问答方案 · 工作流设计',date:'2026.08 — 至今',owner:'内部知识问答 Agent 方案独立设计',status:'方案设计完成 · 尚未实际应用',tag:'Concept prototype',tags:['LLM','Agent','Knowledge Base','Product Design'],lead:'让跨部门资料更容易被找到，同时让访问权限与回答依据保持清晰。',coverLabel:'Concept interface',coverCaption:'为作品集绘制的概念界面；项目状态查询与测试用例生成为规划范围。',phase:'Product concept'},
{slug:'tabletop',category:'INTERACTION × AI',title:'Tabletop AI Atmosphere Renderer',zh:'BOARD-MIND 智能桌游交互设备',desc:'An interactive hardware product combining audio input, ambient feedback and embedded AI.',role:'产品定义 · 原型推进 · 团队协作',date:'2026.02 — 至今',owner:'项目发起人与负责人',status:'第一代实物 → 第二代演示',tag:'Prototype iteration',tags:['Embedded','Audio','Interaction','AI','ESP32-S3'],lead:'让声光跟随桌游阶段变化，把玩家的注意力留在故事里。',coverLabel:'Generation 02 · design model',coverCaption:'第二代设计白模；实物演示和联调资料见 Validation。',phase:'Developed project'},
{slug:'billiards',category:'COMPUTER VISION',title:'AI Billiards Aiming System',zh:'AI 台球瞄准辅助系统',desc:'Exploring computer vision as a usable real-time aiming and decision-support experience.',role:'概念探索 · 交互假设',date:'待补充',owner:'职责与项目经历待补充',status:'概念方案 · 项目证据待补充',tag:'Concept exploration',tags:['Computer Vision','Edge AI','OpenCV','Robotics'],lead:'探索如何把实时视觉信息转化为清晰、可理解的瞄准辅助。',coverLabel:'Design concept',coverCaption:'中性概念示意，非运行截图；技术实现与实测结果待补充。',phase:'Product concept'}
];
projects.push(...resumeProjects);
const projectPriority=['tabletop','badge','bed-robot','tobacco','ai-agent','billiards'];
projects.sort((a,b)=>projectPriority.indexOf(a.slug)-projectPriority.indexOf(b.slug));
const experiences=[
{date:'2026.08 — 至今',org:'长沙市康通电子科技有限公司',role:'AI 体锻机 · 需求分析与产品协作',desc:'对接产品、开发与测试，梳理人脸识别和体测场景需求及验证要点，参与问题复现、定位和联调验证。'},
{date:'2026.07 — 2026.08',org:'深圳市纬尔科技',role:'农业机器人 · 田间联调与验证',desc:'赴新疆开展田间联调，结合漏切、误伤与执行机构响应分析问题，协同工程师优化并完成实机验证。'},
{date:'2026.01',org:'深圳科创学院',role:'机器人研发部 · HMI / 上位机实习',desc:'独立完成串口屏需求梳理、页面架构与交互设计，协调控制端联调，交付可部署的 HMI 工程。'}
];
const processData=[
['Discover','Understand users, problems and opportunities.','用户调研 · 市场分析','从场景观察与需求沟通入手，结合商业调研判断真正值得解决的问题。'],
['Define','Turn insights into clear requirements.','需求分析 · 业务流程 · PRD','拆解功能和优先级，用 TAPD 需求文档对齐业务逻辑、功能边界与验证要点。'],
['Design','Create intuitive and elegant experiences.','Figma 原型 · 交互设计','通过网页 / App 原型、页面架构和关键状态，让产品、开发与测试理解同一套方案。'],
['Build','Engineer and integrate real solutions.','沟通推进 · 项目管理','协调分工与软硬件协作，推进驱动、交互、硬件和整机联调，让方案成为可验证的原型。'],
['Validate','Test, learn and iterate for real-world impact.','数据分析 · 验证 · 汇报','复现问题并验证改动，整理对比与图表，通过评审、路演和复盘推动下一次迭代。']
];
function nav(){return `<header class="nav"><div class="wrap nav-inner"><a class="brand" href="#/" aria-label="Titanfy home">Titanfy</a><nav class="nav-links" id="navigation" aria-label="Main navigation"><a href="#/work">Work</a><a href="#process" data-home-anchor="process">Process</a><a href="#/about">About</a><a href="assets/resume.pdf" target="_blank" rel="noopener" data-cursor="OPEN">Resume</a><a href="#contact" class="nav-contact" data-home-anchor="contact">Contact</a></nav><button class="menu-toggle" aria-controls="navigation" aria-expanded="false" aria-label="Open menu">${icons.menu}</button></div></header>`}
function btn(text,href,secondary=false,extra=''){return `<a href="${href}" class="btn${secondary?' secondary':''}" ${extra}>${text}</a>`}
function sectionHead(eyebrow,title,link=''){return `<div class="section-head"><div><span class="eyebrow">${eyebrow}</span><h2>${title}</h2></div>${link}</div>`}
function visual(p){
let art='';
if(p.slug==='tobacco')art=`<div class="tobacco-art"><span class="art-eyebrow">From problem to requirements</span><div class="workflow-line"><div class="workflow-node">${icons.field}<b>Field needs</b></div><div class="workflow-link"></div><div class="workflow-node">${icons.define}<b>Define</b></div><div class="workflow-link"></div><div class="workflow-node">${icons.build}<b>Build</b></div></div><span class="art-caption">识别目标 → 明确要求 → 执行清理</span></div>`;
if(p.slug==='ai-agent')art=`<div class="agent-art"><div class="agent-window"><div class="agent-top"><span class="agent-dot"></span><span class="agent-dot"></span><span class="agent-dot"></span>Project knowledge</div><div class="agent-body"><span class="agent-chip">当前部门 · 授权资料</span><div class="agent-query">这个项目的需求资料在哪里？</div><div class="agent-response">从已授权的资料中查找答案，<br>并保留可追溯的来源。</div><div class="agent-sources"><span>需求文档 ↗</span><span>来源引用 ↗</span><span>访问范围</span></div></div></div></div>`;
if(p.slug==='tabletop')art='<img src="assets/tabletop-model.png" alt="BOARD-MIND 第二代设计白模" width="534" height="547">';
if(p.slug==='badge')art='<img class="badge-photo" src="assets/badge.jpg" alt="电子吧唧真实交互原型" width="1280" height="1706">';
if(p.slug==='bed-robot')art=`<div class="tobacco-art"><span class="art-eyebrow">A task made testable</span><div class="workflow-line"><div class="workflow-node">${icons.define}<b>Define</b></div><div class="workflow-link"></div><div class="workflow-node">${icons.build}<b>Prototype</b></div><div class="workflow-link"></div><div class="workflow-node">${icons.define}<b>Validate</b></div></div><span class="art-caption">清洁场景 → 核心功能 → 原型验证</span></div>`;
if(p.slug==='billiards')art=`<div class="billiards-art"><svg width="560" height="270" viewBox="0 0 560 270" fill="none" aria-label="台球路径的概念示意"><rect x="25" y="20" width="510" height="225" rx="26" fill="#EEEEF1" stroke="#D7D7DE"/><rect x="42" y="36" width="476" height="193" rx="16" fill="#F8F8FA" stroke="#DCDCE2"/><circle cx="48" cy="42" r="7" fill="#C7C7CF"/><circle cx="280" cy="36" r="7" fill="#C7C7CF"/><circle cx="512" cy="42" r="7" fill="#C7C7CF"/><circle cx="48" cy="222" r="7" fill="#C7C7CF"/><circle cx="280" cy="229" r="7" fill="#C7C7CF"/><circle cx="512" cy="222" r="7" fill="#C7C7CF"/><path d="m136 183 157-69 207-67" stroke="#0071E3" stroke-width="1.5" stroke-dasharray="5 5"/><circle cx="293" cy="114" r="26" stroke="#CADFF6"/><circle cx="136" cy="183" r="10" fill="white" stroke="#A9A9B4"/><circle cx="293" cy="114" r="10" fill="#A4A4AF"/><circle cx="404" cy="190" r="10" fill="#D4D4DB"/><path d="m63 213 52-23" stroke="#B7B7C2" stroke-width="4" stroke-linecap="round"/><path d="M293 74v13m0 54v13m-40-40h13m54 0h13" stroke="#C3D9EF"/></svg></div>`;
return `<div class="card-visual ${p.slug==='tabletop'?'tabletop-cover':''}" data-visual="${p.slug}"><span class="status-label">${p.coverLabel}</span>${art}</div>`;
}
function card(p){return `<a class="card" href="#/work/${p.slug}" data-cursor="VIEW" data-category="${p.phase}">${visual(p)}<div class="card-category">${p.category}</div><h3>${p.title}</h3><p class="card-subtitle">${p.zh}</p><p class="card-description">${p.desc}</p><div class="card-foot"><small>${p.role}<br>${p.tag}</small><span class="card-open" aria-label="View case study">↗</span></div></a>`}
function experience(){return `<section class="section experience" id="experience"><div class="wrap">${sectionHead('04 / EXPERIENCE','Learning in the real world.')}<div class="experience-list">${experiences.map(e=>`<article class="experience-row"><div class="experience-date">${e.date}</div><div><h3>${e.org}</h3><div class="role">${e.role}</div></div><p>${e.desc}</p></article>`).join('')}</div></div></section>`}
function contact(){return `<section class="contact-section" id="contact"><h2>Let's build what's next.</h2><p>Open to product, AI product, technical product,<br>engineering and research opportunities.</p><div class="button-row">${btn('Get In Touch',`mailto:${email}`)}${btn('View Resume','assets/resume.pdf',true,'target="_blank" rel="noopener" data-cursor="OPEN"')}</div><a href="mailto:${email}" class="contact-email">${email}</a></section>`}
function footer(){return `<footer class="footer"><div class="wrap footer-inner"><div><a class="footer-brand" href="#/">Titanfy</a><p>Products built at the intersection<br>of product and technology.</p></div><div><div class="footer-right"><a href="${github}" target="_blank" rel="noopener">GitHub ↗</a><a href="mailto:${email}">Email ↗</a><a href="assets/resume.pdf" target="_blank" rel="noopener">Resume ↗</a></div><div class="copyright">© ${new Date().getFullYear()} Titanfy. All rights reserved.</div></div></div></footer>`}
function capabilities(){const cols=[['PRODUCT',[['需求分析 · Requirement Analysis','场景、功能边界与优先级'],['用户调研 · User Research','场景观察、需求沟通与网络调研'],['逻辑 / 业务流程 · Workflow Design','梳理操作流程与业务逻辑'],['原型设计 · Figma','网页 / App 原型与关键交互状态'],['PRD 文档 · TAPD','需求文档、功能说明与验证要点'],['竞品 / 市场分析 · Product Strategy','商业调研、可行性与产品判断']]],['TECHNOLOGY',[['AI / LLM / Agent Systems','方案设计与 AI 应用验证'],['Robotics & Automation','机器人与自动化实践'],['Embedded Systems','软硬件协同与原型落地'],['Computer Vision / Edge AI','视觉部署与执行器联动'],['Linux','工程环境与工具链']]],['EXECUTION',[['沟通推进 · Collaboration','跨团队对齐与技术沟通'],['项目管理 · Project Management','分工、进度与原型迭代'],['数据分析 · Excel','数据整理、统计对比与图表'],['Testing & Validation','问题复现、整机联调与验证'],['PPT / 汇报 · Presentation','商业计划书、路演与评审沟通']]]];return `<section class="section capabilities" id="capabilities"><div class="wrap">${sectionHead('03 / CORE CAPABILITIES','Product clarity. Technical depth.')}<div class="cap-grid">${cols.map(([title,items])=>`<div class="cap-group"><div class="cap-group-title">${title}</div><div class="cap-list">${items.map(([label,desc])=>`<div class="cap-item">${label}<small>${desc}</small></div>`).join('')}</div></div>`).join('')}</div></div></section>`}
function process(){return `<section class="section process-section" id="process"><div class="wrap"><div class="process-intro"><div><span class="eyebrow">02 / PRODUCT PROCESS</span><h2>Product Process</h2></div><p>From problem to product,<br>with clarity at every step.</p></div><div class="process-steps" role="tablist" aria-label="Product process">${processData.map(([name,desc],i)=>`<button class="process-step ${i===0?'active':''}" role="tab" aria-selected="${i===0}" aria-controls="process-detail" data-step="${i}"><span class="step-num">0${i+1}</span><h3>${name}</h3><p>${desc}</p></button>`).join('')}</div><div class="process-detail" role="tabpanel" id="process-detail"><span class="eyebrow">${processData[0][2]}</span><p>${processData[0][3]}</p></div></div></section>`}
function home(){return `${nav()}<main id="main"><section class="hero"><span class="eyebrow">PRODUCT × TECHNOLOGY × AI</span><h1>Product × Technology × AI</h1><p class="hero-statement">Turning complex ideas<br>into usable products.</p><p class="hero-description">Product thinking, interaction design,<br>and engineering execution across<br>AI, robotics, embedded systems and data.</p><div class="button-row">${btn('View Selected Work','#selected-work')}${btn('About Me','#/about',true)}</div></section><section class="hero-media-section"><div class="hero-media" data-cursor="PAUSE"><video id="hero-video" muted loop playsinline preload="metadata" poster="assets/hero-poster.jpg" aria-label="Titanfy: From Idea to Product"><source src="assets/hero.mp4" type="video/mp4"></video><div class="video-fallback" hidden><p>From idea to product.<br>视频暂时不可用，继续探索下方项目。</p></div><button class="video-toggle" aria-label="Pause hero video">${icons.pause}</button></div><div class="video-caption"><div class="hero-skills"><span>需求分析</span><span>业务流程</span><span>原型设计</span><span>PRD 文档</span><span>沟通推进</span></div><span>From idea to product · 00:12</span></div></section><section class="statement"><h2>Building useful technology<br>for a more open<br>and human future.</h2><p>I believe great products happen at the intersection of<br>deep user understanding, modern technology,<br>and disciplined execution.</p></section><section class="section selected-work" id="selected-work"><div class="wrap">${sectionHead('01 / SELECTED WORK','Selected Work',`<a class="text-link" href="#/work">View All Work <span>→</span></a>`)}<div class="work-grid">${projects.slice(0,2).map(card).join('')}</div><div class="work-grid-bottom">${projects.slice(2).map(card).join('')}</div></div></section>${process()}${capabilities()}${experience()}<section class="section about-section" id="about"><div class="wrap about-grid"><div><span class="eyebrow">05 / ABOUT</span><h2>I like working where<br>product decisions meet<br>technical reality.</h2></div><div class="about-copy"><div class="name">涂腾辉 <span style="color:#86868b;font-size:16px">/ Tenghui Tu</span></div><p>我把用户需求转化为清晰的产品决策，并推进到可验证的原型。实践涵盖 AI 交互、嵌入式硬件与机器人，连接需求、交互、研发和现场验证。</p><div class="education">湖南农业大学 · 湘江卓越工程师学院<br>智能科学与技术本科在读 · 预计 2028.07 毕业</div><a class="text-link" href="#/about">More about my approach <span>→</span></a></div></div></section>${contact()}</main>${footer()}`}
const content={
tobacco:[
['Overview','把清理任务转化为系统方案。','面向烟草收割后的秸秆处理需求，承担整机结构、传动机构、刀辊与电控技术工作，连接需求场景与工程实现。'],
['Problem','收割完成后，清理工作仍未结束。','烟草秸秆处理是农业作业中的具体任务。这个项目关注如何围绕清理目标，把识别、定位与机械执行组织成可协作的系统。'],
['Context','在农业场景中理解设备的工作链路。','项目研发时间为 2024.11 — 2025.07，方向为农业智能装备。我的职责是机械与电控技术，重点在结构方案、驱动与执行环节。'],
['Research','从任务出发，拆解系统需要完成的动作。','以收割后的秸秆处理场景作为方案起点，围绕清理对象、识别定位、机构动作与清理路径展开功能拆解。','<p class="case-note">现有材料未包含独立访谈、竞品研究或田间量化研究记录。</p>'],
['Key Insight','识别目标只是开始，执行链路决定方案能否落地。','清理目标需要贯通视觉定位、机构设计与底层控制，单一模块的完成并不等于整机任务的完成。','quote'],
['Product Decision','围绕同一个清理任务，组织机械与电控。','将整机结构、传动、刀辊和驱动作为相互关联的方案推进，并持续迭代清理路径。','<div class="decision-grid"><div class="decision"><strong>任务层</strong><p>把“处理秸秆”拆为识别目标、坐标转换、执行动作和路径调整。</p></div><div class="decision"><strong>工程层</strong><p>让机构设计与底层驱动围绕相同的目标和执行链路协作。</p></div></div>'],
['Solution','视觉定位 × 机械执行 × 电控协作。','使用视觉识别定位秸秆并解算目标坐标，以整机结构、传动与刀辊承接清理动作，通过驱动及路径迭代逐步整合方案。'],
['Technical Implementation','理解技术边界，让需求能够落地。','负责整机结构、传动机构与刀辊设计；使用 OpenCV / YOLO 识别定位秸秆并解算目标坐标；迭代底层驱动及清理路径。','tech'],
['Validation','从模块完成走向协同验证。','已有机械、电控研发与方案迭代记录。下一步案例材料将补充清理效率、识别效果、现场条件和对照测试，以形成更完整的验证证据。'],
['Outcome','获得项目支持与展示关注。','项目获“金种子计划”5 万元投资支持，并获人民日报、湖南卫视报道。','<div class="outcome-stat">¥50,000</div><p>金种子计划投资支持</p><img class="outcome-img" src="assets/tobacco-outcome.jpg" alt="烟草秸秆项目团队与伍万元支票合影"><p class="case-note">项目成果依据个人简历；报道原文链接待补充。</p>'],
['Reflection','让每个工程选择都有可追溯的需求依据。','后续复盘将聚焦清理流程、方案取舍与现场验证记录，把“为什么这样设计”与“如何验证有效”补充完整。','<p class="case-note">本节为后续复盘与材料整理方向。</p>']
],
'ai-agent':[
['Overview','让知识共享有入口，也有边界。','围绕跨部门信息对接效率问题，独立设计内部知识问答 Agent 方案，规划资料共享、按部门分区和分级授权访问。已完成方案设计，尚未实际应用。'],
['Problem','项目资料共享与访问边界需要同时被考虑。','在产品、开发和测试协作中，信息对接是需求推进的一部分。该方案希望改善跨部门信息对接，同时避免资料权限边界不清。'],
['Context','从 AI 体锻机项目的协作场景出发。','方案形成于长沙市康通电子科技有限公司实习期间，2026.08 — 至今。我参与需求梳理、问题复现、功能联调及验证，并独立完成知识问答 Agent 的方案设计。'],
['Research','先明确问题与资料边界。','已识别跨部门信息对接问题；方案围绕资料归属、共享方式、部门分区与授权层级展开。尚未形成用户访谈、访问日志或效率基线数据。'],
['Key Insight','可找到的知识，也应该是被授权的知识。','共享资料与权限管理需要共同设计：用户不仅需要获得答案，也需要知道答案依据哪些资料、来自哪个访问范围。','quote'],
['Product Decision','以知识问答为核心，分步验证扩展工作流。','首要方案范围是项目知识问答与权限访问。项目状态查询、测试用例生成作为进一步探索的工作流，尚未确认实现。','<div class="decision-grid"><div class="decision"><strong>核心范围 · 已完成方案</strong><p>资料共享、部门分区、分级授权与内部知识问答。</p></div><div class="decision"><strong>扩展范围 · 待验证</strong><p>项目状态查询、基于需求的测试用例生成，以及它们需要的可信数据源。</p></div></div>'],
['Solution','一个入口，清晰的资料范围。','概念界面通过授权范围、问题输入、回答和来源引用表达交互。权限不足或缺少依据时，应明确提示边界，让用户能够继续人工确认。','<p class="case-note">此处为作品集概念原型；界面未接入实际项目资料。</p>'],
['Technical Implementation','先明确系统责任，再选择技术实现。','当前完成的是方案设计，模型、检索管线、索引方式与生产部署尚未确认。实现规划需要围绕资料管理、权限校验、回答依据与业务接口展开。','tech'],
['Validation','从有限、已授权的资料开始验证。','计划先验证答案依据与访问边界，再测试项目状态和用例生成等扩展工作流。目前尚未实际应用，不展示正确率、响应时间或效率提升数据。'],
['Outcome','完成内部知识问答 Agent 方案。','已形成资料共享、部门分区和分级授权的设计方向；实际接入和使用验证仍待推进。'],
['Reflection','把“可以回答”与“应该回答”分开验证。','后续优先补充真实协作流程、授权规则和用户反馈，确保知识问答的可追溯性，再决定如何扩展自动化能力。','<p class="case-note">本节为下一步验证计划。</p>']
],
tabletop:[
['Overview','让桌游中的声光体验跟上故事。','BOARD-MIND 是围绕桌游沉浸体验推进的 AI 交互设备。我作为项目发起人与负责人，连接前期需求、产品定义、商业评估、硬件设计与原型迭代。'],
['Problem','每次手动切换，都是一次注意力中断。','桌游中手动切换声光会分散注意力，氛围反馈也较为单一。产品希望通过语境和桌游阶段的联动，让声光更自然地参与体验。'],
['Context','一个从产品定义推进到实物演示的项目。','项目自 2026.02 持续推进，已经历第一代实物至第二代演示迭代。工作跨越产品方案、软硬件实现、团队分工与整机联调。'],
['Research','把体验问题拆成需求与实现边界。','独立推进前期需求梳理、产品定义、商业评估、立项及路演筹备，围绕桌游中的注意力和氛围反馈形成初始方案。','<p class="case-note">现有材料未提供访谈样本数量与原始研究记录。</p>'],
['Key Insight','声光应该跟随游戏，而不是让游戏等待声光。','把桌游阶段与反馈建立联系，让玩家把注意力留在游戏中，是方案贯穿产品定义与工程实现的核心方向。','quote'],
['Product Decision','将桌游阶段映射为可协同的声光反馈。','规划 AI 语境解析与声光联动，使用上位机 Agent 配合嵌入式设备承接反馈。产品定义与硬件实现并行推进，通过演示版本检验协作链路。','<div class="decision-grid"><div class="decision"><strong>交互决策</strong><p>让反馈与桌游阶段建立联系，减少需要手动切换的环节。</p></div><div class="decision"><strong>推进方式</strong><p>先形成可联调的实物与演示，持续整合上位机、扬声器和灯带。</p></div></div>'],
['Solution','AI 交互方案与桌面设备共同承接体验。','参与上位机 Agent 设计，配合 ESP32-S3 设备的扬声器和 LED 灯带控制，实现桌游阶段与声光反馈联动。'],
['Technical Implementation','产品定义之外，也参与真正的实现。','负责硬件选型、PCB 设计、SolidWorks 建模、布线与嵌入式软件。基于 ESP32-S3 完成扬声器驱动和 LED 灯带控制，参与上位机 Agent 设计与软硬件集成。','tech'],
['Validation','从第一代实物，推进到第二代演示。','统筹团队分工、软硬件协作与整机联调，持续推进原型迭代。以下为真实项目资料，展示设计与实物的不同阶段。','<div class="evidence-grid"><figure><img src="assets/tabletop-v1.jpg" alt="BOARD-MIND 第一代实物"><figcaption>01 / 第一代实物</figcaption></figure><figure><img src="assets/tabletop-v2.jpg" alt="BOARD-MIND 第二代演示"><figcaption>02 / 第二代演示</figcaption></figure><figure><img src="assets/tabletop-model.png" alt="第二代设计白模"><figcaption>03 / 第二代结构设计白模</figcaption></figure><figure><img src="assets/tabletop-board.jpg" alt="BOARD-MIND 项目电路板"><figcaption>04 / 电路与硬件实现</figcaption></figure></div>'],
['Outcome','获得认可，并进入展示与迭代。','项目获湘江科技创新院认可及展示机会，已形成从首代实物到二代演示的可见迭代成果。'],
['Reflection','把“能联动”继续推进到“更合适地反馈”。','后续验证将关注反馈时机、误触发和对游戏注意力的影响，并保留人工控制入口。下一次迭代需要更多体验证据来支持产品判断。','<p class="case-note">本节为后续用户验证方向；不代表已经完成的测试结果。</p>']
],
billiards:[
['Overview','一次关于视觉辅助的产品概念探索。','探索如何把实时计算机视觉转化为可理解的瞄准辅助。本案例目前为概念方案，项目时间、个人职责、实现证据与测试结果待补充。'],
['Problem','看见更多数据，不一定更容易做决定。','概念问题是：如何让视觉检测结果成为可理解的击球方向提示，而不增加使用者的判断负担？'],
['Context','产品概念阶段。','当前范围是球台视觉信息、目标与建议路径的交互表达。没有已确认的运行原型、部署平台或量化性能数据。'],
['Research','计划先验证用户的判断过程。','研究计划：观察用户如何判断击球方向，了解哪些视觉提示有帮助、哪些提示造成干扰，再界定实时辅助的必要信息。尚无实测记录。'],
['Key Insight','让系统解释提示，而不是只输出坐标。','工作假设：清晰的目标、路径与识别状态，比堆叠底层视觉数据更适合支持判断。该假设尚未验证。','quote'],
['Product Decision','优先表达目标、路径与系统状态。','拟先展示可理解的瞄准提示，保留识别失败、低置信状态与人工判断，避免把未经验证的建议表现为确定答案。','<div class="decision-grid"><div class="decision"><strong>正常状态 · 概念</strong><p>识别球台与目标，呈现建议路径以及当前视觉状态。</p></div><div class="decision"><strong>失败状态 · 概念</strong><p>遮挡或识别不确定时，明确提示重新观察与人工判断。</p></div></div>'],
['Solution','以中性的球台视图组织提示。','当前概念原型包含球台、目标球和建议路径示意，用于评估信息层级与可读性；这不是已运行系统的截图。'],
['Technical Implementation','技术范围待方案与证据进一步明确。','拟探索 Computer Vision、Edge AI 与 OpenCV 的实现方向；模型、硬件平台、算法细节与运行状态均未确认。','tech'],
['Validation','验证方法与结果待补充。','需要补充原型演示、识别条件、路径计算方法与测试记录，再评估可读性、稳定性和实时性。'],
['Outcome','概念方向已定义，实际成果待补充。','当前保留产品概念与信息组织方案，不展示未经证实的准确率、延迟、使用者数量或商业成果。'],
['Reflection','先建立证据，再扩大功能范围。','后续先确认项目职责、时间和实现状态，再用真实测试验证视觉信息是否帮助使用者理解并做出判断。','<p class="case-note">整个案例为概念探索，尚不构成已完成工程项目的证明。</p>']
]};
function casePage(slug){if(slug==="tabletop"||slug==="tabletop/technology")return nav()+window.TitanfyBoard.page(slug.endsWith("/technology"))+footer();const p=projects.find(p=>p.slug===slug);if(!p)return workPage();const secs=content[slug];const next=projects[(projects.indexOf(p)+1)%projects.length];return `${nav()}<main id="main"><section class="page-intro"><div class="wrap"><a class="breadcrumb" href="#/work">← All work</a><span class="eyebrow">${p.category} / CASE STUDY</span><h1>${p.title}</h1><p class="intro-subtitle">${p.zh}</p><p class="lead">${p.lead}</p><dl class="case-meta"><div><dt>My role</dt><dd>${p.owner}</dd></div><div><dt>Timeline</dt><dd>${p.date}</dd></div><div><dt>Status</dt><dd>${p.status}</dd></div></dl></div></section><section class="case-cover"><div class="wrap">${visual(p)}<div class="case-cover-caption"><span>${p.coverCaption}</span><span>Product thinking → Engineering execution</span></div></div></section><section class="case-content"><div class="wrap case-layout"><aside class="case-index"><span class="eyebrow">IN THIS CASE STUDY</span>${secs.map(([name],i)=>`<a href="#case-${i+1}">${String(i+1).padStart(2,'0')} &nbsp; ${name}</a>`).join('')}</aside><article class="case-story">${secs.map(([name,title,body,extra],i)=>`<section class="case-section" id="case-${i+1}"><span class="eyebrow">${String(i+1).padStart(2,'0')} / ${name}</span><h2 class="zh">${title}</h2>${extra==='quote'?`<div class="insight-quote"><p>${body}</p><small>${slug==='billiards'?'待验证的工作假设':'基于方案的设计归纳'}</small></div>`:`<p>${body}</p>${extra==='tech'?`<div class="tech-chips">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div>`:extra||''}`}</section>`).join('')}<a class="next-case" href="#/work/${next.slug}"><div><span class="eyebrow">NEXT CASE STUDY</span><h2>${next.title}</h2></div><span class="next-arrow">↗</span></a></article></div></section>${contact()}</main>${footer()}`}
function workPage(){return `${nav()}<main id="main"><section class="page-intro all-work-head"><div class="wrap"><a class="breadcrumb" href="#/">← Home</a><span class="eyebrow">SELECTED PROJECTS / 01 — 06</span><h1>Ideas made tangible.</h1><p class="lead">产品问题、方案取舍与实现过程。<br>每个案例先讲为什么，再讲如何落地。</p></div></section><section class="section"><div class="wrap"><div class="all-work-intro"><div class="filter-list" aria-label="Filter work"><button class="filter active" data-filter="all" aria-pressed="true">All work</button><button class="filter" data-filter="Developed project" aria-pressed="false">Developed projects</button><button class="filter" data-filter="Product concept" aria-pressed="false">Product concepts</button></div><span id="work-count">06 projects</span></div><div class="work-list-grid">${projects.map(card).join('')}</div></div></section>${contact()}</main>${footer()}`}
function aboutPage(){return `${nav()}<main id="main"><section class="page-intro"><div class="wrap"><a class="breadcrumb" href="#/">← Home</a><div class="about-page-intro"><div><span class="eyebrow">ABOUT / TENGHUI TU</span><h1>Product decisions.<br>Technical reality.</h1><p class="intro-subtitle">涂腾辉 · 嵌入式硬件 / AI 硬件产品方向</p><p class="lead">我从用户需求出发，组织产品方案，<br>再通过工程实践理解它能否真正落地。</p><div class="resume-inline">${btn('View Resume','assets/resume.pdf',false,'target="_blank" rel="noopener"')}${btn('Get In Touch',`mailto:${email}`,true)}</div></div><div class="about-portrait"><img src="assets/portrait.jpg" alt="涂腾辉个人照片"></div></div></div></section><section class="section"><div class="wrap">${sectionHead('01 / MY APPROACH','From understanding to execution.')}<div class="about-evidence"><article class="evidence-tile"><span class="eyebrow">01 / UNDERSTAND</span><h3>Ask better questions.</h3><p>结合场景观察、需求沟通和商业调研识别问题，拆解功能与优先级，用数据整理和对比支持判断。</p></article><article class="evidence-tile"><span class="eyebrow">02 / MAKE IT CLEAR</span><h3>Make ideas discussable.</h3><p>使用 Figma 原型、业务流程和 TAPD 需求文档表达方案，用路演、评审和汇报对齐不同角色。</p></article><article class="evidence-tile"><span class="eyebrow">03 / MAKE IT REAL</span><h3>Build, test, learn.</h3><p>推进团队分工、软硬件协作与整机联调，在原型迭代和现场验证中不断修正产品判断。</p></article></div></div></section>${capabilities()}<section class="section"><div class="wrap">${sectionHead('02 / ENGINEERING DEPTH','A practical understanding of technology.')}<div class="mini-project"><div><h3>Embedded & hardware</h3><small>嵌入式软件 · 结构与电路</small></div><p>C / C++、Python；STM32、ESP32-S3 / ESP-IDF、FreeRTOS。具备原理图与 PCB 设计、SolidWorks 建模、驱动开发及整机联调实践。</p></div><div class="mini-project"><div><h3>AI & computer vision</h3><small>AI 应用 · 视觉部署与验证</small></div><p>参与上位机 Agent 设计；具备 OpenCV / YOLO 目标定位、树莓派部署与视觉执行器联动实践。参与 RK3588 摄像头、YOLO-Face / ArcFace 接口及 MediaPipe Pose 验证。</p></div><div class="mini-project"><div><h3>Robotics & HMI</h3><small>控制 · 交互 · 现场验证</small></div><p>HMI 页面与串口协议设计；PID / ADRC、编码器与 IMU 融合实践；Linux / Ubuntu、Git、ROS 2 / Gazebo，以及农业机器人田间联调。</p></div></div></section>${experience()}<section class="section about-section"><div class="wrap">${sectionHead('03 / MORE PRODUCT PRACTICE','Different products. The same curiosity.')}<div class="mini-project"><div><h3>二次元电子吧唧</h3><small>2026.01 — 至今 · 商业调研、软件研发与硬件协同</small><a class="text-link" href="https://github.com/titfly77-cyber/emotion_screen" target="_blank" rel="noopener">Explore source ↗</a></div><p>面向潮玩与陪伴场景，将动作触发、表情音效和内容更新转化为功能。推进商业可行性分析、计划书与路演，基于 ESP32-S3 / FreeRTOS 完成初代演示和原型迭代。</p></div><div class="mini-project"><div><h3>扫床机器人</h3><small>2026.04 · 产品方向与嵌入式软件方向负责人</small></div><p>围绕自动扫床场景规划方案、核心功能与实现路径，开展商业分析与评审沟通，协调分工并推进差速底盘、里程计、巡线 / 避障的原型验证。</p></div><div class="mini-project"><div><h3>持续学习与协作</h3><small>湖南农业大学 · 智能科学与技术</small></div><p>本科在读，预计 2028.07 毕业。农业人工智能实验室成员、智慧农业协会副会长。参与跨校团队协作、社会实践调研与项目汇报；可用英语介绍产品并开展技术沟通。</p></div></div></section>${contact()}</main>${footer()}`}
Object.assign(content,resumeCases);
const baseAboutPage=aboutPage;
aboutPage=function(){return baseAboutPage().replace(contact(),resumeExtras()+contact())};
let currentRoute='';let cleanup=()=>{};
function setup(){const menu=document.querySelector('.menu-toggle');menu?.addEventListener('click',()=>{const n=document.querySelector('.nav-links');const open=n.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu')});
document.querySelectorAll('[data-home-anchor]').forEach(a=>a.addEventListener('click',e=>{if(currentRoute!=='/'){e.preventDefault();window.__pendingHomeAnchor=a.dataset.homeAnchor;location.hash='/'}}));
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-pressed',String(n===b))});let count=0;document.querySelectorAll('.work-list-grid .card').forEach(c=>{c.hidden=b.dataset.filter!=='all'&&b.dataset.filter!==c.dataset.category;if(!c.hidden)count++});document.getElementById('work-count').textContent=String(count).padStart(2,'0')+' projects'}));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;window.TitanfyOpening.prepare();const motionCleanup=window.TitanfyMotion.mount({icons,processData});const openingCleanup=window.TitanfyOpening.mount();const boardCleanup=window.TitanfyBoard.mount();
const cursor=document.querySelector('.cursor-label');const fine=matchMedia('(hover: hover) and (pointer: fine)').matches;const move=e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';const target=e.target.closest('[data-cursor]');if(target&&!reduced&&fine){cursor.textContent=target.dataset.cursor;cursor.classList.add('visible')}else cursor.classList.remove('visible')};if(fine&&!reduced)document.addEventListener('pointermove',move);cleanup=()=>{boardCleanup();openingCleanup();motionCleanup();document.removeEventListener('pointermove',move);cursor.classList.remove('visible')};
}
function route(event){const hash=event?.type==='prototype:motion-preference'?currentRoute:location.hash.slice(1);if(hash&&!hash.startsWith('/'))return;window.__prototypeReady=false;window.TitanfyMotion.navigate(()=>{cleanup();currentRoute=hash||'/';document.getElementById('app').innerHTML=currentRoute==='/about'?aboutPage():currentRoute==='/work'?workPage():currentRoute.startsWith('/work/')?casePage(currentRoute.slice(6)):home();window.scrollTo({top:0,behavior:'instant'});setup();document.title=(currentRoute==='/'?'Titanfy':currentRoute==='/about'?'About — Titanfy':currentRoute==='/work'?'Selected Work — Titanfy':(projects.find(p=>p.slug===currentRoute.slice(6))?.title||'Work')+' — Titanfy')+' · Product × Technology × AI';document.fonts.ready.then(()=>{window.__prototypeReady=true;if(window.__pendingHomeAnchor&&currentRoute==='/'){const id=window.__pendingHomeAnchor;delete window.__pendingHomeAnchor;document.getElementById(id)?.scrollIntoView({behavior:'instant'})}})},Boolean(currentRoute)&&hash!=='/work/tabletop');}
window.addEventListener('hashchange',route);window.addEventListener('prototype:motion-preference',route);route();


