import * as T from 'three';
import {GLTFLoader} from './assets/board/GLTFLoader.js';
const cache=new Map();
function load(name){if(!cache.has(name))cache.set(name,new GLTFLoader().loadAsync('./assets/board/'+name).catch(e=>{cache.delete(name);throw e;}));return cache.get(name);}
export function mountBoard(stage){
 const viewer=stage.querySelector('.board-viewer'),status=stage.querySelector('[role=status]'),replay=stage.querySelector('.board-replay');stage.querySelector('.board-particles').hidden=true;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,mobile=innerWidth<600,count=mobile?9000:24000;
 let disposed=false,raf=0,renderer,scene,camera,pivot,white,colored,geometry,material,ready=false,start=0,last=performance.now(),exit=0,active=false,particlesInitialized=false;
 const revealUniform={value:0},pointer={x:0,y:0},positions=new Float32Array(count*3),colors=new Float32Array(count*3),sizes=new Float32Array(count),seeds=new Float32Array(count*4);
 const palette=['#536cff','#7447ec','#a171f1','#6792ff'].map(c=>new T.Color(c));let seed=2718;function random(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
 for(let i=0;i<count;i++){for(let j=0;j<4;j++)seeds[i*4+j]=random();const c=palette[i%4];colors.set([c.r,c.g,c.b],i*3);sizes[i]=.65+random()*1.15;}
 const noiseCode=`varying vec3 vErosionPosition;uniform float uReveal;
 float grain(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}
 float cloud(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(mix(grain(i),grain(i+vec3(1,0,0)),f.x),mix(grain(i+vec3(0,1,0)),grain(i+vec3(1,1,0)),f.x),f.y),mix(mix(grain(i+vec3(0,0,1)),grain(i+vec3(1,0,1)),f.x),mix(grain(i+vec3(0,1,1)),grain(i+vec3(1,1,1)),f.x),f.y),f.z);}`;
 function erosion(m,isColor){m.traverse(n=>{if(!n.isMesh)return;for(const mat of Array.isArray(n.material)?n.material:[n.material]){mat.onBeforeCompile=shader=>{shader.uniforms.uReveal=revealUniform;shader.vertexShader='varying vec3 vErosionPosition;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvErosionPosition=(modelMatrix*vec4(transformed,1.0)).xyz;');shader.fragmentShader=noiseCode+'\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <clipping_planes_fragment>',`#include <clipping_planes_fragment>
 float field=clamp(.31*(vErosionPosition.y+1.7)/3.4+.37*cloud(vErosionPosition*3.8)+.22*cloud(vErosionPosition*15.0)+.10*grain(floor(vErosionPosition*155.0)),.005,.995);
 ${isColor?'if(uReveal<field)discard;':'if(uReveal>=field)discard;'}`);shader.fragmentShader=shader.fragmentShader.replace('#include <dithering_fragment>',`#include <dithering_fragment>
 float edge=(1.0-smoothstep(0.0,.034,abs(field-uReveal)))*step(.01,uReveal)*(1.0-step(.99,uReveal));gl_FragColor.rgb=mix(gl_FragColor.rgb,vec3(.32,.23,.95),edge*.65);`);};mat.customProgramCacheKey=()=>isColor?'board-erosion-color-v2':'board-erosion-white-v2';}});}
 function normalize(source){const m=source.scene.clone(true),box=new T.Box3().setFromObject(m),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()),scale=3/Math.max(size.x,size.y,size.z);m.position.sub(center).multiplyScalar(scale);m.scale.setScalar(scale);m.traverse(n=>{if(n.isMesh)n.material=Array.isArray(n.material)?n.material.map(a=>a.clone()):n.material.clone();});return m;}
 function resize(){if(!renderer)return;renderer.setSize(viewer.clientWidth,viewer.clientHeight);camera.aspect=viewer.clientWidth/viewer.clientHeight;camera.updateProjectionMatrix();if(material)material.uniforms.uPixelRatio.value=Math.min(devicePixelRatio,1.5);}
 function move(e){if(reduced)return;const r=stage.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width-.5;pointer.y=(e.clientY-r.top)/r.height-.5;active=e.clientY>=r.top&&e.clientY<=r.bottom;}function leave(){active=false;}
 function scroll(){exit=Math.min(1,Math.max(0,-stage.parentElement.getBoundingClientRect().top/(innerHeight*.6)));stage.style.setProperty('--model-opacity',String(1-exit));}
 async function init(){try{renderer=new T.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0xfafafa,0);renderer.toneMapping=T.ACESFilmicToneMapping;viewer.append(renderer.domElement);scene=new T.Scene();scene.add(new T.HemisphereLight(0xffffff,0x9999aa,3));for(const [x,y,z,intensity]of [[4,6,5,5],[-4,2,-3,3]]){const light=new T.DirectionalLight(0xffffff,intensity);light.position.set(x,y,z);scene.add(light);}camera=new T.PerspectiveCamera(mobile?40:34,1,.01,100);camera.position.set(4.6,2.7,5.7);camera.lookAt(0,0,0);pivot=new T.Group();scene.add(pivot);
 geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(positions,3).setUsage(T.DynamicDrawUsage));geometry.setAttribute('color',new T.BufferAttribute(colors,3));geometry.setAttribute('aSize',new T.BufferAttribute(sizes,1));material=new T.ShaderMaterial({transparent:true,depthWrite:false,depthTest:true,vertexColors:true,uniforms:{uOpacity:{value:.72},uPixelRatio:{value:1}},vertexShader:'attribute float aSize;varying vec3 vColor;uniform float uPixelRatio;void main(){vColor=color;vec4 p=modelViewMatrix*vec4(position,1.0);gl_PointSize=clamp(aSize*uPixelRatio*8.0/-p.z,.65,3.0);gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 vColor;uniform float uOpacity;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;float a=(1.0-smoothstep(.06,.5,d))*uOpacity;gl_FragColor=vec4(vColor,a);}' });const stars=new T.Points(geometry,material);stars.frustumCulled=false;stars.renderOrder=3;scene.add(stars);resize();
 const models=await Promise.all([load('crystal_white_model.glb'),load('crystal_rendered.glb')]);if(disposed)return;white=normalize(models[0]);colored=normalize(models[1]);erosion(white,false);erosion(colored,true);pivot.add(white,colored);await renderer.compileAsync(scene,camera);if(disposed)return;start=performance.now();ready=true;stage.querySelector('.board-poster').hidden=true;status.textContent='粒子持续环绕 · 移动鼠标调整视角';window.__boardReady=true;window.__boardParticleCount=count;}catch(e){if(disposed)return;status.textContent='三维预览暂不可用，可继续查看项目资料';stage.querySelector('.board-poster').src='assets/board/rendered.png';window.__boardError=String(e);}}
 function frame(now){if(disposed)return;const dt=Math.min(30,(now-last)/16.67);last=now;const reveal=ready?(typeof window.__boardCaptureReveal==='number'?window.__boardCaptureReveal:reduced?1:Math.min(1,Math.max(0,(now-start-650)/4600))):0;revealUniform.value=reveal;const time=reduced?0:now*.00016;
 if(ready){white.visible=reveal<1;colored.visible=reveal>0;if(!reduced&&reveal===1){pivot.rotation.y+=((active?pointer.x*.4:0)-pivot.rotation.y)*(1-Math.pow(.95,dt));pivot.rotation.x+=((active?pointer.y*.08:0)-pivot.rotation.x)*(1-Math.pow(.95,dt));}
 const spring=reduced||!particlesInitialized?1:1-Math.pow(.83,dt);for(let i=0;i<count;i++){const s=i*4,k=i*3,u=seeds[s]*Math.PI*2+time,v=(seeds[s+1]-.5)*1.15,dust=(seeds[s+2]-.5)*.065;
 // Half-twist ribbon in world space; depth testing hides its rear behind the device.
 const radius=2.04+v*Math.cos(u/2),mx=radius*Math.cos(u),mz=radius*Math.sin(u),my=v*Math.sin(u/2),tilt=.40+pointer.y*.22,ringY=my*Math.cos(tilt)-mz*Math.sin(tilt),ringZ=my*Math.sin(tilt)+mz*Math.cos(tilt);
 let x=mx,y=ringY,z=ringZ;
 x+=dust+Math.cos(u)*exit*9;y+=dust+Math.sin(u)*exit*7;z+=dust;positions[k]+=(x-positions[k])*spring;positions[k+1]+=(y-positions[k+1])*spring;positions[k+2]+=(z-positions[k+2])*spring;
 }particlesInitialized=true;geometry.attributes.position.needsUpdate=true;material.uniforms.uOpacity.value=(1-exit)*(reveal<1?.82:.65);if(exit<1&&!document.hidden)renderer.render(scene,camera);window.__boardReveal=reveal;window.__boardRotation=pivot.rotation.y;window.__boardParticleMode=exit>=1?'hidden':'mobius';window.__boardErosion=true;}raf=requestAnimationFrame(frame);}
 function restart(){if(ready){pivot.rotation.set(0,0,0);start=performance.now();scrollTo({top:0,behavior:'smooth'});}}replay.onclick=restart;window.__boardReady=false;delete window.__boardError;addEventListener('pointermove',move,{passive:true});document.documentElement.addEventListener('pointerleave',leave);addEventListener('blur',leave);addEventListener('scroll',scroll,{passive:true});addEventListener('resize',resize);scroll();init();raf=requestAnimationFrame(frame);
 return()=>{disposed=true;cancelAnimationFrame(raf);removeEventListener('pointermove',move);document.documentElement.removeEventListener('pointerleave',leave);removeEventListener('blur',leave);removeEventListener('scroll',scroll);removeEventListener('resize',resize);for(const m of [white,colored])m?.traverse(n=>{if(n.isMesh)for(const a of Array.isArray(n.material)?n.material:[n.material])a.dispose();});geometry?.dispose();material?.dispose();renderer?.dispose();renderer?.forceContextLoss();renderer?.domElement.remove();window.__boardReady=false;};
}



