const clamp=(n,a=0,b=1)=>Math.min(b,Math.max(a,n));
export function mountScroll(root,reduce){
 let frame=0,disposed=false;const cleanups=[];
 const sketch=root.querySelector('.sketch-story'),art=root.querySelector('.portrait-art'),passes=[...root.querySelectorAll('.ink-pass')];
 const regions=[[602,70,465,334,.02,.36,.32],[642,279,410,348,.14,.58,-.2],[613,491,482,307,.28,.73,.28],[416,590,426,370,.35,.86,-.24],[796,510,610,445,.43,.92,.32],[-20,-20,1712,981,.66,1,.21]];
 let inkPaths=[];
 if(art){const dark=passes[0].querySelector('img').src;const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 1672 941');svg.setAttribute('class','ink-canvas');svg.setAttribute('aria-hidden','true');const defs=document.createElementNS(ns,'defs'),mask=document.createElementNS(ns,'mask');mask.id='sketch-drawing';mask.setAttribute('maskUnits','userSpaceOnUse');mask.setAttribute('x','0');mask.setAttribute('y','0');mask.setAttribute('width','1672');mask.setAttribute('height','941');regions.forEach(([x,y,w,h,start,end,angle])=>{const path=document.createElementNS(ns,'path');let lines=[];for(let yy=y-140;yy<y+h+140;yy+=6)lines.push(`M ${x} ${yy} L ${x+w} ${yy+angle*w}`);path.setAttribute('d',lines.join(' '));path.setAttribute('fill','none');path.setAttribute('stroke','white');path.setAttribute('stroke-linecap','round');path.setAttribute('stroke-width',reduce.matches?'7.9':'.001');mask.append(path);inkPaths.push(path)});defs.append(mask);svg.append(defs);const image=document.createElementNS(ns,'image');image.setAttribute('href',dark);image.setAttribute('width','1672');image.setAttribute('height','941');image.setAttribute('mask','url(#sketch-drawing)');svg.append(image);passes.forEach(p=>p.remove());art.append(svg)}
 const process=root.querySelector('.process-story'),nav=[...root.querySelectorAll('.process-nav li')],panels=[...root.querySelectorAll('.process-panel')],track=root.querySelector('.process-track span');let active=-1;
 const glass=root.querySelector('.education-glass'),education=root.querySelector('.education-story');
 const scenes=[...root.querySelectorAll('.experience-scene')];
 const manifesto=root.querySelector('.manifesto-english');
 const progress=el=>{const rect=el.getBoundingClientRect();return clamp(-rect.top/(el.offsetHeight-innerHeight||1))};
 function resize(){schedule()}
 function update(){frame=0;if(disposed)return;if(sketch){const p=reduce.matches?1:progress(sketch);sketch.dataset.progress=p.toFixed(3);inkPaths.forEach((el,i)=>{const [x,y,w,h,start,end]=regions[i];const t=clamp((p-start)/(end-start));el.setAttribute('stroke-width',String(Math.max(.001,7.9*t)))})}
 if(process&&!reduce.matches){const p=progress(process),index=Math.min(4,Math.floor(p*5));if(index!==active){active=index;nav.forEach((el,i)=>el.classList.toggle('active',i===index));panels.forEach((el,i)=>{el.classList.toggle('active',i===index);el.setAttribute('aria-hidden',String(i!==index))});root.querySelector('#process-count').textContent=String(index+1).padStart(2,'0')}if(track)track.style.width=p*100+'%'}
 if(glass&&!reduce.matches){const r=education.getBoundingClientRect();const p=clamp((innerHeight-r.top)/(innerHeight+r.height));glass.style.transform=`translateY(${-90*p}px)`}
 scenes.forEach(scene=>{if(reduce.matches)return;const r=scene.getBoundingClientRect();if(r.top<innerHeight&&r.bottom>0){const p=clamp((innerHeight-r.top)/(innerHeight+r.height));scene.querySelector('.experience-image img').style.transform=`translateY(${(p-.5)*65}px) scale(1.1)`}});
 if(manifesto&&!reduce.matches){const r=manifesto.closest('.manifesto').getBoundingClientRect();const p=clamp(-r.top/(r.height*.6));manifesto.style.transform=`translate(${-p*innerWidth*.16}px,${-p*45}px) scale(${1-p*.32})`}
 }
 function schedule(){if(!frame&&!disposed)frame=requestAnimationFrame(update)}
 addEventListener('scroll',schedule,{passive:true});addEventListener('resize',resize);reduce.addEventListener('change',schedule);resize();
 const video=root.querySelector('#home-video');if(video){const play=root.querySelector('#hero-play');let visible=false,userPaused=false;const sync=()=>play.textContent=video.paused?'▶ 播放':'Ⅱ 暂停';const io=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible&&!reduce.matches&&!userPaused)video.play().catch(sync);else video.pause();sync()},{threshold:.4});io.observe(video);play.onclick=()=>{if(video.paused){userPaused=false;video.play().catch(sync)}else{userPaused=true;video.pause()}sync()};video.addEventListener('play',sync);video.addEventListener('pause',sync);const visibility=()=>{if(document.hidden)video.pause();else if(visible&&!userPaused&&!reduce.matches)video.play().catch(sync)};document.addEventListener('visibilitychange',visibility);cleanups.push(()=>{io.disconnect();video.pause();document.removeEventListener('visibilitychange',visibility)})}
 return ()=>{disposed=true;cancelAnimationFrame(frame);removeEventListener('scroll',schedule);removeEventListener('resize',resize);reduce.removeEventListener('change',schedule);cleanups.forEach(fn=>fn())};
}
